version: "3"
services:
  fastapi:
    build:
      context: ./app
      dockerfile: ../dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./app:/app"
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres

    ports:
      - "6800:5432"
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres-db:
